In [1]:
import numpy as np
array1 = np.array([2,3, 5, 7, 11, 13, 17, 19])

In [2]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19])

In [3]:
type(array1)

numpy.ndarray

In [4]:
array1.shape

(8,)

# np.array 배열 만들기

In [6]:
a2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [7]:
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
type(a2)

numpy.ndarray

In [9]:
a2.shape

(3, 4)

## array에 같은 숫자 채우기

### np.full((행,열),숫자) or np.full(행,숫자)

In [13]:
array3 = np.full((6,7),0)
array4 = np.random.random(6)

In [14]:
array3

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [12]:
array4

array([0.73532881, 0.64204856, 0.8311306 , 0.9232698 , 0.88669664,
       0.27604796])

In [15]:
revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

In [16]:
type(revenue_in_yen)

list

In [17]:
yen = np.array(revenue_in_yen)

In [18]:
yen

array([300000, 340000, 320000, 360000, 440000, 140000, 180000, 340000,
       330000, 290000, 280000, 380000, 170000, 140000, 230000, 390000,
       400000, 350000, 380000, 150000, 110000, 240000, 380000, 380000,
       340000, 420000, 150000, 130000, 360000, 320000, 250000])

In [19]:
yen.shape

(31,)

In [20]:
won = yen * 10.08

In [21]:
won

array([3024000., 3427200., 3225600., 3628800., 4435200., 1411200.,
       1814400., 3427200., 3326400., 2923200., 2822400., 3830400.,
       1713600., 1411200., 2318400., 3931200., 4032000., 3528000.,
       3830400., 1512000., 1108800., 2419200., 3830400., 3830400.,
       3427200., 4233600., 1512000., 1310400., 3628800., 3225600.,
       2520000.])

## array 안의 타입 바꾸기

### 특정array.astype(int)

In [24]:
won.astype(int)

array([3024000, 3427200, 3225600, 3628800, 4435200, 1411200, 1814400,
       3427200, 3326400, 2923200, 2822400, 3830400, 1713600, 1411200,
       2318400, 3931200, 4032000, 3528000, 3830400, 1512000, 1108800,
       2419200, 3830400, 3830400, 3427200, 4233600, 1512000, 1310400,
       3628800, 3225600, 2520000])

## array 간의 합

In [26]:
(won + won).astype(int)

array([6048000, 6854400, 6451200, 7257600, 8870400, 2822400, 3628800,
       6854400, 6652800, 5846400, 5644800, 7660800, 3427200, 2822400,
       4636800, 7862400, 8064000, 7056000, 7660800, 3024000, 2217600,
       4838400, 7660800, 7660800, 6854400, 8467200, 3024000, 2620800,
       7257600, 6451200, 5040000])

## array의 인덱싱 index

In [27]:
arrayi = np.array ([2,3,5,7,11,13,15,17,19,23])

In [28]:
arrayi

array([ 2,  3,  5,  7, 11, 13, 15, 17, 19, 23])

In [30]:
arrayi[0]

2

In [31]:
arrayi[-1]

23

### index 여러 개 = [[x, y, z]]

In [35]:
arrayi[[0, 3]]

array([2, 7])

In [37]:
arrayi[[0, 9, 2]]

array([ 2, 23,  5])

### index Slice = [::]

In [40]:
arrayi[0:3]

array([2, 3, 5])

In [41]:
arrayi[0:9:2]

array([ 2,  5, 11, 15, 19])

## Numpy 기본연산

### 파이썬의 range = np.arrange()

In [42]:
array1 = np.arange(10)
array2 = np.arange(10,20)

In [44]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
array1 *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
array1 +2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
array1 -2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [47]:
array1 /2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [48]:
array1 **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [50]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [54]:
array1 = np.arange(1,10)
array2 = np.arange(10,20)

In [53]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### array 간의 +,-,*,/는 인덱스 길이가 같아야 가능

In [56]:
array1 + array2

ValueError: operands could not be broadcast together with shapes (9,) (10,) 

In [57]:
array1 = np.arange(0,10)

In [58]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [60]:
array1 +array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [61]:
array1 - array2

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [62]:
array1 * array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [63]:
array1 / array2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

## Numpy 불린 연산(boolean)

In [64]:
array1 = np.array ([2,3,5,7,11,13,17,19,23,29])
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [65]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [66]:
array1 %2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False])

In [69]:
boolean = np.array([False,True,False,False,False,False,False,False,False,True])

### numpy.where(x)함수 ==> 몇 번 인덱스에 x가 있냐

In [70]:
np.where(boolean)

(array([1, 9], dtype=int64),)

In [71]:
np.where(array1 >4 )

(array([2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

### array[x]  ==> x값에 numpy.where()값을 넣어줄 수 있음

In [72]:
array1[np.where(array1 >4)]

array([ 5,  7, 11, 13, 17, 19, 23, 29])

In [73]:
array1[np.where(boolean)]

array([ 3, 29])