In [1]:
import pandas as pd
import numpy as np

### 데이터 백터 저장하기

In [8]:
score1 = np.array([96, 80, 76, 96, 88, 75, 78])
score2 = np.array([67, 83, 76, 96, 88, 75, 78])

In [9]:
score = np.append(score1, score2)
print(score)

[96 80 76 96 88 75 78 67 83 76 96 88 75 78]


- 데이터 수평결합

In [10]:
sc = np.hstack([score1, score2])
print(sc)

[96 80 76 96 88 75 78 67 83 76 96 88 75 78]


* 숫자의 올림, 내림, 버림, 반올림

In [14]:
import math
z = math.ceil(2.54864) #올림
print(z)
z = math.floor(2.54864) #내림
print(z)
z = math.trunc(2.54864) #버림
print(z)
z = round(2.54864, 2) # 소수점 이하 2 자리 반올림
print(z)

3
2
2
2.55


### 기초 통계량 구하기

In [36]:
import scipy as sp
import numpy as np

In [37]:
score1 = np.array([96, 80, 76, 96, 88, 75, 78])

In [38]:
np.amin(score1) # 최소값

75

In [39]:
np.amax(score1) # 최대값

96

In [42]:
score1/np.std(score1, ddof=1) #표준화

array([10.507,  8.756,  8.318, 10.507,  9.632,  8.209,  8.537])

In [43]:
score1/np.std(score1, ddof=0) #표준화(unbiased var)

array([11.349,  9.458,  8.985, 11.349, 10.403,  8.867,  9.221])

In [45]:
from scipy import stats
stats.scoreatpercentile(score1, 25) # 25 percentile

77.0

### 행, 열별 함수 적용하기

* 데이터프레임 생성

In [56]:
df = pd.DataFrame({
    'Alphabet' : ['a','b','c','d','e','f','g','h','i','j'],
    'num' : [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
    'length' : np.arange(10)
})
df # python의 dict와 비슷

Alphabet  num  length
0        a    3       0
1        b    3       1
2        c    3       2
3        d    3       3
4        e    3       4
5        f    3       5
6        g    3       6
7        h    3       7
8        i    3       8
9        j    3       9

In [57]:
df.mean() #열 별 평균, 계산할 수 없는 열은 자동으로 넘어감

num       3.0
length    4.5
dtype: float64

In [59]:
df.mean(axis=0) # column 별 평균

num       3.0
length    4.5
dtype: float64

In [61]:
df.mean(axis=1) # row 별 평균

0    1.5
1    2.0
2    2.5
3    3.0
4    3.5
5    4.0
6    4.5
7    5.0
8    5.5
9    6.0
dtype: float64

* 순서함수

In [67]:
a = [3,2,1,4,5]

In [68]:
sorted(a)

[1, 2, 3, 4, 5]

In [69]:
np.sort(a) #array로 반환

array([1, 2, 3, 4, 5])

In [70]:
sorted(a, reverse=True)

[5, 4, 3, 2, 1]

In [71]:
a.sort() # 정렬된 값이 a에 적용됨
a

[1, 2, 3, 4, 5]

* 순서함수의 활용

In [74]:
df = pd.DataFrame({
    'name' : ['KIM', 'LEE', 'PARK', 'BAE'],
    'age' : [24, 32, 24, np.nan],
    'height' : [160, 170, 180, 155]
})
df

name   age  height
0   KIM  24.0     160
1   LEE  32.0     170
2  PARK  24.0     180
3   BAE   NaN     155

In [77]:
df['age_rank'] = df['age'].rank(method = 'min', ascending=False, na_option='bottom')
df

name   age  height  age_rank
0   KIM  24.0     160       2.0
1   LEE  32.0     170       1.0
2  PARK  24.0     180       2.0
3   BAE   NaN     155       4.0

In [78]:
# ascending=False  :  내림차순 정렬
# method = 'min'   :   동점일 경우 최솟값 할당
# na_option='bottom'   : 결측값은 후순위 할당

* 결측치를 선순위를 주고자 할 경우

In [79]:
df['age_rank'] = df['age'].rank(method = 'min', ascending=False, na_option='top')
df

name   age  height  age_rank
0   KIM  24.0     160       3.0
1   LEE  32.0     170       2.0
2  PARK  24.0     180       3.0
3   BAE   NaN     155       1.0

* DataFrame 안에서 'name'을 기준으로 순서함수 적용하기

In [80]:
df_sort_name = df.sort_values(by='name')  # 오름차순 배열
df_sort_name

name   age  height  age_rank
3   BAE   NaN     155       1.0
0   KIM  24.0     160       3.0
1   LEE  32.0     170       2.0
2  PARK  24.0     180       3.0

In [81]:
df_sort_name = df.sort_values(by='name', ascending=False)  # 내림차순 배열
df_sort_name

name   age  height  age_rank
2  PARK  24.0     180       3.0
1   LEE  32.0     170       2.0
0   KIM  24.0     160       3.0
3   BAE   NaN     155       1.0